export namespace Flag {
  export const KUYACODE_AUTO_SHARE = truthy("KUYACODE_AUTO_SHARE")
  export const KUYACODE_GIT_BASH_PATH = process.env["KUYACODE_GIT_BASH_PATH"]
  export const KUYACODE_CONFIG = process.env["KUYACODE_CONFIG"]
  export const KUYACODE_CONFIG_DIR = process.env["KUYACODE_CONFIG_DIR"]
  export const KUYACODE_CONFIG_CONTENT = process.env["KUYACODE_CONFIG_CONTENT"]
  export const KUYACODE_DISABLE_AUTOUPDATE = truthy("KUYACODE_DISABLE_AUTOUPDATE")
  export const KUYACODE_DISABLE_PRUNE = truthy("KUYACODE_DISABLE_PRUNE")
  export const KUYACODE_DISABLE_TERMINAL_TITLE = truthy("KUYACODE_DISABLE_TERMINAL_TITLE")
  export const KUYACODE_PERMISSION = process.env["KUYACODE_PERMISSION"]
  export const KUYACODE_DISABLE_DEFAULT_PLUGINS = truthy("KUYACODE_DISABLE_DEFAULT_PLUGINS")
  export const KUYACODE_DISABLE_LSP_DOWNLOAD = truthy("KUYACODE_DISABLE_LSP_DOWNLOAD")
  export const KUYACODE_ENABLE_EXPERIMENTAL_MODELS = truthy("KUYACODE_ENABLE_EXPERIMENTAL_MODELS")
  export const KUYACODE_DISABLE_AUTOCOMPACT = truthy("KUYACODE_DISABLE_AUTOCOMPACT")
  export const KUYACODE_DISABLE_MODELS_FETCH = truthy("KUYACODE_DISABLE_MODELS_FETCH")
  export const KUYACODE_DISABLE_CLAUDE_CODE = truthy("KUYACODE_DISABLE_CLAUDE_CODE")
  export const KUYACODE_DISABLE_CLAUDE_CODE_PROMPT =
    KUYACODE_DISABLE_CLAUDE_CODE || truthy("KUYACODE_DISABLE_CLAUDE_CODE_PROMPT")
  export const KUYACODE_DISABLE_CLAUDE_CODE_SKILLS =
    KUYACODE_DISABLE_CLAUDE_CODE || truthy("KUYACODE_DISABLE_CLAUDE_CODE_SKILLS")
  export const KUYACODE_FAKE_VCS = process.env["KUYACODE_FAKE_VCS"]
  export const KUYACODE_CLIENT = process.env["KUYACODE_CLIENT"] ?? "cli"
  export const KUYACODE_SERVER_PASSWORD = process.env["KUYACODE_SERVER_PASSWORD"]
  export const KUYACODE_SERVER_USERNAME = process.env["KUYACODE_SERVER_USERNAME"]

  // Experimental
  export const KUYACODE_EXPERIMENTAL = truthy("KUYACODE_EXPERIMENTAL")
  export const KUYACODE_EXPERIMENTAL_FILEWATCHER = truthy("KUYACODE_EXPERIMENTAL_FILEWATCHER")
  export const KUYACODE_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("KUYACODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const KUYACODE_EXPERIMENTAL_ICON_DISCOVERY =
    KUYACODE_EXPERIMENTAL || truthy("KUYACODE_EXPERIMENTAL_ICON_DISCOVERY")
  export const KUYACODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("KUYACODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const KUYACODE_ENABLE_EXA =
    truthy("KUYACODE_ENABLE_EXA") || KUYACODE_EXPERIMENTAL || truthy("KUYACODE_EXPERIMENTAL_EXA")
  export const KUYACODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("KUYACODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const KUYACODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("KUYACODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const KUYACODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("KUYACODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const KUYACODE_EXPERIMENTAL_OXFMT = KUYACODE_EXPERIMENTAL || truthy("KUYACODE_EXPERIMENTAL_OXFMT")
  export const KUYACODE_EXPERIMENTAL_LSP_TY = truthy("KUYACODE_EXPERIMENTAL_LSP_TY")
  export const KUYACODE_EXPERIMENTAL_LSP_TOOL = KUYACODE_EXPERIMENTAL || truthy("KUYACODE_EXPERIMENTAL_LSP_TOOL")
  export const KUYACODE_EXPERIMENTAL_PLAN_MODE = KUYACODE_EXPERIMENTAL || truthy("KUYACODE_EXPERIMENTAL_PLAN_MODE")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
